linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - typecheck
    - gocritic
    - revive
    - misspell
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - testdata
    - integration/testdata
    - mocks

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
