name: Build / Base Image

on:
  push:
    branches: [ master ]
    paths:
      - '.github/docker/base.Dockerfile'
      - '.github/workflows/build-base-image.yml'
  pull_request:
    paths:
      - '.github/docker/base.Dockerfile'
      - '.github/workflows/build-base-image.yml'
  workflow_dispatch:

concurrency:
  group: base-image
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/base

jobs:
  build-and-publish:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment:
      name: Registry
      url: https://github.com/${{ github.repository }}/pkgs/container/stack-auditor%2Fbase

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Registry Authentication
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and Publish Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/docker/base.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
