name: Build Base Image

on:
  push:
    branches: [ master ]
    paths:
      - '.github/docker/base.Dockerfile'
  pull_request:
    paths:
      - '.github/docker/base.Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/base

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment:
      name: Registry
      url: ${{ steps.deployment.outputs.url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/docker/base.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set deployment URL
        id: deployment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHA_TAG=$(echo '${{ steps.meta.outputs.tags }}' | grep sha | head -n1 | cut -d: -f2)

          PACKAGE_ID=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            "https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${{ github.event.repository.name }}%2Fbase/versions" \
            | jq -r ".[] | select(.metadata.container.tags[] | contains(\"$SHA_TAG\")) | .id")
 
          echo "url=https://github.com/${{ github.repository }}/pkgs/container/${{ github.event.repository.name }}%2Fbase/$PACKAGE_ID?tag=$SHA_TAG" >> $GITHUB_OUTPUT
