name: Tests / Unit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    strategy:
      fail-fast: true
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Go Environment
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true
        cache: true

    - name: Install Test Framework
      run: go install github.com/onsi/ginkgo/v2/ginkgo@v2
      
    - name: Execute Unit Tests
      run: |
        set -e
        ginkgo -r -v --label-filter="!integration" --keep-going --trace --randomize-all
