name: Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  go-unit-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Go Environment
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true
        cache: true

    - name: Install Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo@v2
      
    - name: Run Unit Tests
      run: |
        set -e
        ginkgo -r -v --label-filter="!integration" --keep-going --trace --randomize-all
