name: Update Plugin Repository

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (e.g., v1.2.3)'
        type: string
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  update-plugin-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Download release assets
        env:
          VERSION: ${{ inputs.version }}
        run: |
          mkdir -p dist
          base_url="https://github.com/cloudfoundry/stack-auditor/releases/download/${VERSION}"
          curl -L "${base_url}/stack-auditor-linux-64"     -o "dist/stack-auditor-linux-64"
          curl -L "${base_url}/stack-auditor-darwin-amd64" -o "dist/stack-auditor-darwin-amd64"
          curl -L "${base_url}/stack-auditor-darwin-arm"   -o "dist/stack-auditor-darwin-arm"
          curl -L "${base_url}/stack-auditor-windows-64"   -o "dist/stack-auditor-windows-64"

      - name: Calculate SHA1s
        id: sha1
        run: |
          echo "linux_sha1=$(sha1sum dist/stack-auditor-linux-64 | cut -d ' ' -f 1)"            >> $GITHUB_OUTPUT
          echo "darwin_amd64_sha1=$(sha1sum dist/stack-auditor-darwin-amd64 | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
          echo "darwin_arm_sha1=$(sha1sum dist/stack-auditor-darwin-arm | cut -d ' ' -f 1)"     >> $GITHUB_OUTPUT
          echo "windows_sha1=$(sha1sum dist/stack-auditor-windows-64 | cut -d ' ' -f 1)"        >> $GITHUB_OUTPUT

      - name: Checkout cli-plugin-repo
        uses: actions/checkout@v4
        with:
          repository: cloudfoundry/cli-plugin-repo
          path: cli-plugin-repo

      - name: Update repo-index.yml
        working-directory: cli-plugin-repo
        env:
          VERSION:           ${{ inputs.version }}
          LINUX_SHA1:        ${{ steps.sha1.outputs.linux_sha1 }}
          DARWIN_AMD64_SHA1: ${{ steps.sha1.outputs.darwin_amd64_sha1 }}
          DARWIN_ARM_SHA1:   ${{ steps.sha1.outputs.darwin_arm_sha1 }}
          WINDOWS_SHA1:      ${{ steps.sha1.outputs.windows_sha1 }}
        run: |
          version="${VERSION#v}"  # Remove 'v' prefix
          base_url="https://github.com/cloudfoundry/stack-auditor/releases/download/${VERSION}"

          echo "::group::Orginal repo-index.yml"
          cat repo-index.yml
          echo "::endgroup::"

          # Update version
          sed -i -E "/(name: stack-auditor)/{n;n;n;s/version: .*/version: ${version}/}" repo-index.yml

          # Update Linux
          sed -i -E "/(name: stack-auditor).*platforms:.*linux64/,/sha1:/{s|url: .*|url: ${base_url}/stack-auditor-linux-64|;s/sha1: .*/sha1: ${LINUX_SHA1}/}" repo-index.yml

          # Update Darwin AMD64
          sed -i -E "/(name: stack-auditor).*platforms:.*osx/,/sha1:/{s|url: .*|url: ${base_url}/stack-auditor-darwin-amd64|;s/sha1: .*/sha1: ${DARWIN_AMD64_SHA1}/}" repo-index.yml

          # Update Darwin ARM64
          sed -i -E "/(name: stack-auditor).*platforms:.*darwin/,/sha1:/{s|url: .*|url: ${base_url}/stack-auditor-darwin-arm|;s/sha1: .*/sha1: ${DARWIN_ARM_SHA1}/}" repo-index.yml

          # Update Windows
          sed -i -E "/(name: stack-auditor).*platforms:.*win64/,/sha1:/{s|url: .*|url: ${base_url}/stack-auditor-windows-64|;s/sha1: .*/sha1: ${WINDOWS_SHA1}/}" repo-index.yml

          echo "::group::Modified repo-index.yml"
          cat repo-index.yml
          echo "::endgroup::"

          echo "::group::Diff repo-index.yml"
          git diff -- repo-index.yml
          echo "::endgroup::"
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: cli-plugin-repo
        run: |
          version="${{ inputs.version }}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          branch_name="update-stack-auditor-${version}"
          git checkout -b "$branch_name"

          git add repo-index.yml
          git commit -m "Update stack-auditor to ${version}"
          git push origin "$branch_name"

          gh pr create \
            --title "Update stack-auditor to ${version}" \
            --body  "Updates stack-auditor plugin to version ${version} for all supported platforms" \
            --repo  a-b/cli-plugin-repo \
            --base  master \
            --draft
